# Netlify configuration file

[build]
  # This is the directory where the build command will be run.
  base = "/Users/yuhanc/pdf-power-tools/"
  # This is the directory that contains the built site.
  publish = "/Users/yuhanc/pdf-power-tools/dist"
  # This is the command that will be run to build the site.
  command = "npm run build"

[[redirects]]
  # This rule tells Netlify to redirect all requests to index.html
  # so that client-side routing can take over.
  from = "/*"
  to = "/index.html"
  status = 200
